### PR TITLE
Provide a mechanism to express TS type unions from Java

### LINKED ISSUE #61: Provide a mechanism to express TS type unions from Java
Unlike many of the other ideas in JS, closure js, and typescript, Java doesn't have a type union feature, with the exception of in `catch()` expressions. JsInterop handles this case by generating new types which express each of the possible unioned types, with 'isFoo' methods that return boolean, and 'asFoo' that return the value cast to that type. The `@JsType` for those union types incorrectly states that they map to `?` in closure JS, so there is no way from jsinterop alone to work backwards to closure JS here.

Instead, I propose that we author union types in Java, with specific annotations to explain that this is a union between several other types. We can't simply annotate the type with `@TsUnion(String.class, Number.class)` or the like, since it wouldn't be possible to pass `JsArray<String>` in there as well, so actual members that match the possible types are required.

Example of jsinterop and elemental2, using [`fetch(resource)`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax) (omitting options for the sake of simplicity):
```java
  public static native Promise<Response> fetch(DomGlobal.FetchInputUnionType input);

  @JsOverlay
  public static final Promise<Response> fetch(Request input) {
    return fetch(Js.<DomGlobal.FetchInputUnionType>uncheckedCast(input), init);
  }

  @JsOverlay
  public static final Promise<Response> fetch(String input) {
    return fetch(Js.<DomGlobal.FetchInputUnionType>uncheckedCast(input), init);
  }

  @JsType(isNative = true, name = "?", namespace = JsPackage.GLOBAL)
  public interface FetchInputUnionType {
    @JsOverlay
    static DomGlobal.FetchInputUnionType of(Object o) {
      return Js.cast(o);
    }

    @JsOverlay
    default Request asRequest() {
      return Js.cast(this);
    }

    @JsOverlay
    default String asString() {
      return Js.asString(this);
    }

    @JsOverlay
    default boolean isRequest() {
      return (Object) this instanceof Request;
    }

    @JsOverlay
    default boolean isString() {
      return (Object) this instanceof String;
    }
  }
```

As can be seen from the overloads, either a String or a Request can be specified to this method, but the actual underlying JS method is only defined once - the implementation will have to test which object is passed. In the same way, if a Java method were defined that takes some union type, JS could call it with either type, and the Java code would have to test the type of the parameter.

In closure JS, this is defined as (again, omitting the options/init):
```javascript
/**
 * @typedef {!Request|!URL|string}
 * @see https://fetch.spec.whatwg.org/#requestinfo
 */
var RequestInfo;

/**
 * @param {!RequestInfo} input
 * @return {!Promise<!Response>}
 * @see https://fetch.spec.whatwg.org/#fetch-method
 */
function fetch(input) {}
```

In typescript, we might define this instead as
```typescript
fetch(input:string|Request):Promise<Response>
```

---

Since this tool starts only from java and we can control the TS output, I suggest we use a union type in this way to describe an API that is flexible in what types can be used. The example input Java here creates a native type mapped to `?`, and provides only the required convenience methods to _read_ the values (writing them is optional, and need only exist if other Java would call this code), but still has to behave in the jsinterop type system as a native type. Unioning with null is still supported via `@JsNullable`. This means all methods on the union type are `@JsOverlay`.

```java
@JsType
public interface Api {
  ResultUnion<String> someFunction(ParamUnion param1, @JsNullable ParamUnion param2);
}

@JsType(isNative=true, name="?", namespace=JsPackage.GLOBAL)
@TsUnion// Proposed annotation on the type itself 
public interface ResultUnion<T> {//generics can be supported, but need not be used on each constituent type
   // one optional way for java to be able to directly create these, has no effect on ts output
  @JsOverlay
  static <T> ResultUnion<T>  of(Object o) { return Js.cast(o); }

  @JsOverlay
  @TsUnionMember// Proposed annotation for methods to indicate that this return type is only of the possible types
  default Double asNumber() {...}

  @JsOverlay
  @TsUnionMember
  default JsArray<T> asArray() {...}
}

@JsType(isNative=true, name="?", namespace=JsPackage.GLOBAL)
@TsUnion// Proposed annotation on the type itself 
public interface ParamUnion {
  // since this is a param type, java has no real need for creator methods


  @JsOverlay
  @TsUnionMember
  default Double asNumber() {...}

  // another demonstration of a complex type
  @JsOverlay
  @TsUnionMember
  default JsArray<@JsNullable String> asNullableStringArray() {...}


}
```
Note that both TsUnion and TsUnionMember are probably not both needed, but might make for added clarity. 

There is some flexibility in what we can generate here, but at least for now I suggest emitting the union inline, without a named typedef:

```typescript
interface Api {
  someFunction(param1:Array<string | null>|number, param2:Array<string | null>|number|null|undefined):number|Array<string>; 
}
```

### PR DESCRIPTION
**Pull request by vegegoku**
Fixes #61

### CODE REVIEW

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsNullableType.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package com.vertispan.tsdefs.model;
+
+public class TsNullableType extends TsType implements IsNullableTsType {
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsNullableType.java:18]: any thoughts on just making this call into the TsUnionType?

File: jsinterop-ts-defs-annotations/src/main/java/com/vertispan/tsdefs/annotations/TsUnion.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+import java.lang.annotation.Documented;
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+/**
+ * A type annotated with this annotation will be exported as interface, even if the type itself is
+ * not an interface if a type is extending a type that is annotated as TsInterface when exported it
+ * will implement the exported interface instead of extending,
```
Comment (niloc132) [inline jsinterop-ts-defs-annotations/src/main/java/com/vertispan/tsdefs/annotations/TsUnion.java:27]: comment incomplete

File: jsinterop-ts-defs-annotations/src/main/java/com/vertispan/tsdefs/annotations/TsUnionMember.java [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+import java.lang.annotation.Documented;
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+/**
+ * A type annotated with this annotation will be exported as interface, even if the type itself is
+ * not an interface if a type is extending a type that is annotated as TsInterface when exported it
+ * will implement the exported interface instead of extending,
```
Comment (niloc132) [inline jsinterop-ts-defs-annotations/src/main/java/com/vertispan/tsdefs/annotations/TsUnionMember.java:27]: comment incomplete

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsNullableType.java [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+  private final TsType type;
+  private boolean undefined = true;
+
+  public TsNullableType(TsType type) {
+    super(type.name, type.namespace);
+    this.type = type;
+  }
+
+  public static TsNullableType of(TsType tsType) {
+    return new TsNullableType(tsType);
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsNullableType.java:29]: maybe check if input is already instanceof TsNullableType, if so just return it without wrapping again?

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsNullableType.java [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+ * limitations under the License.
+ */
+package com.vertispan.tsdefs.model;
+
+public class TsNullableType extends TsType implements IsNullableTsType {
+
+  private final TsType type;
+  private boolean undefined = true;
+
+  public TsNullableType(TsType type) {
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsNullableType.java:23]: probably should be private

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsUnionType.java [hunk 6]
```diff
@@ -16,26 +16,40 @@
...
+            this.tsTypes.addAll(((TsUnionType) tsType).tsTypes);
+          } else {
+            this.tsTypes.add(tsType);
+          }
+        });
   }
 
   public static TsUnionType of(TsType... types) {
-    return new TsUnionType(Arrays.asList(types));
+    return new TsUnionType(new HashSet<>(Arrays.asList(types)));
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsUnionType.java:42]: Java 11: Set.of(types)... but this should probably preserve order, since TsUnionType.tsTypes is a linkedhashset

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsUnionType.java [hunk 7]
```diff
@@ -16,26 +16,40 @@
...
+import java.util.Set;
 import java.util.stream.Collectors;
 
 public class TsUnionType extends TsType {
 
-  private List<TsType> tsTypes;
+  private final Set<TsType> tsTypes = new LinkedHashSet<>();
 
-  public TsUnionType(List<TsType> tsTypes) {
+  public TsUnionType(Set<TsType> tsTypes) {
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsUnionType.java:28]: Consider Collection<TsType> instead since you already iterate through it

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsUnionType.java [hunk 8]
```diff
@@ -16,26 +16,40 @@
...
-    this.tsTypes = tsTypes;
+
+    tsTypes.forEach(
+        tsType -> {
+          if (tsType instanceof TsUnionType) {
+            this.tsTypes.addAll(((TsUnionType) tsType).tsTypes);
+          } else {
+            this.tsTypes.add(tsType);
+          }
+        });
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsUnionType.java:38]: could also be this, remove the initialized value on the field

```suggestion
    this.tsTypes = tsTypes.stream()
        .flatMap(type -> {
          if (type instanceof TsUnionType) {
            return ((TsUnionType) type).tsTypes.stream();
          }
          return Stream.of(tsType);
        })
        .collect(Collectors.toCollection(LinkedHashSet::new));
```
or something in between here and there

**Review by niloc132 — APPROVED** [review]
