### PR TITLE
Nullable generic type is mangled

### LINKED ISSUE #36: Nullable generic type is mangled
Given an a generic type that is nullable, the various components of the type are emitted in the wrong order.

Example java type;
```java
@JsNullable JsArray<String>
```
Expected output:
```typescript
Array<string>|null|undefined
```
Actual output:
```typescript
Array|null|undefined<string>
```

Long term we're probably going to need to create a TypeUnion (with a list of other ts types) and a GenericType, so that composing types like this can't break in this way, but for now just reordering how the type name is printed will solve this.

### PR DESCRIPTION
**Pull request by vegegoku**
fix #36 `|null|undefined` is not correctly placed for generic types.

### CODE REVIEW

File: jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsType.java [hunk 1]
```diff
@@ -59,10 +59,14 @@ public TsType addBounds(TsType tsType) {
...
+    return emitType(parentNamespace) + emitNullable();
+  }
+
+  protected String emitType(String parentNamespace) {
     if (namespace.isEmpty() || namespace.equals(parentNamespace)) {
-      return resolveName(name) + emitBounds(parentNamespace) + emitNullable();
+      return resolveName(name) + emitBounds(parentNamespace);
     } else {
-      return namespace + "." + resolveName(name) + emitBounds(parentNamespace) + emitNullable();
+      return namespace + "." + resolveName(name) + emitBounds(parentNamespace);
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/main/java/com/vertispan/tsdefs/model/TsType.java:69]: I noted this in the ticket, but I think that arrays need to be adjusted as well.

File: jsinterop-ts-defs-processor/src/test/java/com/vertispan/tsdefs/jsnullable/JsTypeWithJsNullableMembers.java [hunk 2]
```diff
@@ -26,6 +28,13 @@ public class JsTypeWithJsNullableMembers {
   public String notNullable;
 
   public @JsNullable String nullableProperty;
+  public @JsNullable JsArray<String> nullableStringJsArray;
+  public JsArray<@JsNullable String> jsArrayOfNullableStrings;
+  public @JsNullable JsArray<@JsNullable String> nullableArrayOfNullableStrings;
+  public @JsNullable JsMap<@JsNullable String, @JsNullable Double>
+      nullableMapOfNullableKeysAndValues;
+  public @JsNullable JsMap<@JsNullable String, Double> nullableMapOfNullableKeys;
+  public @JsNullable JsMap<String, @JsNullable Double> nullableMapOfNullableValues;
```
Comment (niloc132) [inline jsinterop-ts-defs-processor/src/test/java/com/vertispan/tsdefs/jsnullable/JsTypeWithJsNullableMembers.java:37]: test for String[] too please

**Review by niloc132 — APPROVED** [review]
